# This is a basic workflow that is manually triggered

name: test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
jobs:
  build:
    name: test-job
    runs-on: windows-2019
    steps:

    - name: Setup-mongo
      shell: pwsh
      run: |
        mkdir /temp/mongodb
        #Start-Job -ScriptBlock { mongod --dbpath /temp/mongodb --replSet tr0 --bind_ip 127.0.0.1 }
        mongod --dbpath /temp/mongodb --replSet tr0 --bind_ip 127.0.0.1 
        Start-Sleep -s 5
        mongo --eval 'rs.initiate()'
    - name: Test-connection
      shell: pwsh
      run: mongo --eval 'exit'
    - name: Shutdown-mongo
      shell: pwsh
      run: |
          mongo --eval "db.getSiblingDB('admin').shutdownServer()"
      
      
